
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    Connection conn;
    ButtonGroup bg=new ButtonGroup();
     ArrayList<Integer> list = new ArrayList<Integer>();
     int cnt=1;
     String ans;
     int ans1;
     int anss=0;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        conn=DBConnection.ConnectionDB();
        bg.add(jRadioButton1);
         bg.add(jRadioButton2);
          bg.add(jRadioButton3);
           bg.add(jRadioButton4);
           getQuiz();
           showQuiz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        jButton3.setText("End Exam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton4)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            try {
                String str=bg.getSelection().getActionCommand();
               if(str.equals(ans))
               {
                   ans1=1;
                   anss++;
               }
               
                String sql="insert into user_info(user_name,ques,ans) values('"+ans+"','"+cnt+"','"+ans1+"')";
                PreparedStatement pst=conn.prepareStatement(sql);
                int data=pst.executeUpdate();
                if(data>0)
                {
                    JOptionPane.showMessageDialog(null, "Your Answer is Stored");
                   
                }
                    cnt++;
                    showQuiz();
                    bg.clearSelection();
                
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
       

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Do you want to Stop the Exam");
       
       
            JOptionPane.showMessageDialog(null, "You Got "+anss);
            System.exit(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

    private void getQuiz() {
        //To change body of generated methods, choose Tools | Templates.
               
        for (int i=1; i<6; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        
        for (int i=0; i<5; i++) {
            
             System.out.println(list.get(i));
        }
        
       
        
    }

    private void showQuiz() {
        //To change body of generated methods, choose Tools | Templates.
        ans1=0;
         for (int j=list.size()-1;j>=0;j--) {
            
         }
         if(cnt==1)
         {
        try {
                String sql="select ques_no,ques,a,b,c,d,ques_ans from javaquiz where ques_no='"+cnt+"'";
                PreparedStatement pst=conn.prepareStatement(sql);
                ResultSet rst=pst.executeQuery();
                if(rst.next())
                {
                    int a=rst.getInt(1);
                    String r=Integer.toString(a);
                    jLabel1.setText("Q."+rst.getString(2));
                   String aa=rst.getString(3);
                   jRadioButton1.setText(aa);
                    jRadioButton1.setActionCommand(aa);
                     String b=rst.getString(4);
                     jRadioButton2.setText(b);
                      jRadioButton2.setActionCommand(b);
                       String c=rst.getString(5);
                       jRadioButton3.setText(c);
                        jRadioButton3.setActionCommand(c);
                         String d=rst.getString(6);
                          jRadioButton4.setText(d);
                          jRadioButton4.setActionCommand(d);
                          ans=rst.getString(7);
                    
                    
                    
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if(cnt==2)
         {
        try {
                String sql="select ques_no,ques,a,b,c,d,ques_ans from javaquiz where ques_no='"+cnt+"'";
                PreparedStatement pst=conn.prepareStatement(sql);
                ResultSet rst=pst.executeQuery();
                if(rst.next())
                {
                    int a=rst.getInt(1);
                    String r=Integer.toString(a);
                    jLabel1.setText("Q."+rst.getString(2));
                    String aa=rst.getString(3);
                   jRadioButton1.setText(aa);
                    jRadioButton1.setActionCommand(aa);
                     String b=rst.getString(4);
                     jRadioButton2.setText(b);
                      jRadioButton2.setActionCommand(b);
                       String c=rst.getString(5);
                       jRadioButton3.setText(c);
                        jRadioButton3.setActionCommand(c);
                         String d=rst.getString(6);
                          jRadioButton4.setText(d);
                          jRadioButton4.setActionCommand(d);
                          ans=rst.getString(7);
                    
                    
                    
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if(cnt==3)
         {
        try {
                String sql="select ques_no,ques,a,b,c,d,ques_ans from javaquiz where ques_no='"+cnt+"'";
                PreparedStatement pst=conn.prepareStatement(sql);
                ResultSet rst=pst.executeQuery();
                if(rst.next())
                {
                    int a=rst.getInt(1);
                    String r=Integer.toString(a);
                    jLabel1.setText("Q."+rst.getString(2));
                    String aa=rst.getString(3);
                   jRadioButton1.setText(aa);
                    jRadioButton1.setActionCommand(aa);
                     String b=rst.getString(4);
                     jRadioButton2.setText(b);
                      jRadioButton2.setActionCommand(b);
                       String c=rst.getString(5);
                       jRadioButton3.setText(c);
                        jRadioButton3.setActionCommand(c);
                         String d=rst.getString(6);
                          jRadioButton4.setText(d);
                          jRadioButton4.setActionCommand(d);
                          ans=rst.getString(7);
                    
                    
                    
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if(cnt==4)
         {
        try {
                String sql="select ques_no,ques,a,b,c,d,ques_ans from javaquiz where ques_no='"+cnt+"'";
                PreparedStatement pst=conn.prepareStatement(sql);
                ResultSet rst=pst.executeQuery();
                if(rst.next())
                {
                    int a=rst.getInt(1);
                    String r=Integer.toString(a);
                    jLabel1.setText("Q."+rst.getString(2));
                    String aa=rst.getString(3);
                   jRadioButton1.setText(aa);
                    jRadioButton1.setActionCommand(aa);
                     String b=rst.getString(4);
                     jRadioButton2.setText(b);
                      jRadioButton2.setActionCommand(b);
                       String c=rst.getString(5);
                       jRadioButton3.setText(c);
                        jRadioButton3.setActionCommand(c);
                         String d=rst.getString(6);
                          jRadioButton4.setText(d);
                          jRadioButton4.setActionCommand(d);
                          ans=rst.getString(7);
                    
                    
                    
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if(cnt==5)
         {
             JOptionPane.showMessageDialog(null, "You Got "+anss);
             System.exit(0);
         }
    }
    
}
